name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: simple-cluster
  GKE_ZONE: europe-north1-a
  DEPLOYMENT_NAME: test-k8s
  IMAGE: charkasau/simple-api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build
        run: docker build -t "charkasau/simple-api:$GITHUB_SHA" .

      - name: Docer log in
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Publish
        run: docker push charkasau/simple-api:$GITHUB_SHA

      - name: Deploy
        run: kubectl apply -f k8s
