name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: simple-cluster
  GKE_ZONE: europe-north1-a
  DEPLOYMENT_NAME: test-k8s
  IMAGE: charkasau/simple-api:$GITHUB_SHA

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Prepare config
        run: gcloud container clusters get-credentials "simple-cluster" --region=europe-north1-a
      - name: Prepare gplugin
        run: sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Build
        run: docker build -t charkasau/simple-api -t charkasau/simple-api:$GITHUB_SHA .

      - name: Docker log in
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push latest
        run: docker push charkasau/simple-api:latest
      - name: Push sha
        run: docker push charkasau/simple-api:$GITHUB_SHA

      - name: Deploy
        run: kubectl apply -f k8s
