name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: simple-cluster
  GKE_ZONE: europe-north1-a
  DEPLOYMENT_NAME: test-k8s
  IMAGE: charkasau/simple-api:$GITHUB_SHA
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Prepare config
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null;
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update kubectl
          gcloud container clusters get-credentials "simple-cluster" --region=europe-north1-a

      - name: Build
        run: docker build -t charkasau/simple-api -t charkasau/simple-api:$GITHUB_SHA .

      - name: Publish
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push charkasau/simple-api:latest
          docker push charkasau/simple-api:$GITHUB_SHA

      - name: Deploy
        run: |
          gcloud components update kubectl
          gcloud container clusters get-credentials "simple-cluster" --region=europe-north1-a
          kubectl apply -f k8s
